### ISSUE TITLE
Create a lighter version of this image

### ISSUE THREAD

**Issue by NaimHusain** [riazarbi/datasci-gui-gpu#2]
Hello, Thank you for providing theses images to the community. I would like to use this image, however the python libraries are causing the image to have an excessive size (16Gb). Would it be possible to publish a version of this image without the python libraries pre-installed ? 

I tried doing it myself, however the dockerfile fails to build due to an error in with apt.

King regards,

Naïm

**Comment by riazarbi** [comment]
Hi @NaimHusain , I don't really use this image anymore, and was actually going to retire it soon. I haven't kept track of the state of docker-with-GPUs, but it looks to me like there are better ways of doing it right now. I'll do some investigating and, if I come up with a better solution I'll tag it in this issue.

**Comment by NaimHusain** [comment]
Hello, thank you for answering, I managed to fix the build of the dockerfile by rotating the signing keys as explained here : 
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772

I also found another way to reduce the image size by starting from the official image jupyter/datascience-notebook:ubuntu-20.04 and resinstalling RStudio and the CUDA drivers the same way you did in your images

Thank you again for your work, I'll keep an eye your repos !


Naïm
